### ISSUE TITLE
Deformable-Conv编译后运行报错及解决

### ISSUE THREAD

**Issue by steermomo** [steermomo/steermomo.github.io#7]
https://i.steer.space/blog/2021/01/Build-MSAttn-in-Deformable-DETR

**Comment by 9p15p** [comment]
哥，你到底改啥了呀。啥也没有变呀

**Comment by steermomo** [comment]
> 哥，你到底改啥了呀。啥也没有变呀

@9p15p 
-DCUDA_HAS_FP16=0

**Comment by 9p15p** [comment]
谢谢大哥，好使，3090上也会出现这个问题。奇了怪了。照您这样做才能跑
